name: Scheduled Ticket Scrape

on:
  schedule:
    - cron: '0 8 * * *'   # Läuft täglich um 08:00 UTC (09:00 Wien-Zeit im Winter, 10:00 im Sommer)
  workflow_dispatch:       # Manuelles Starten im GitHub-UI

jobs:
  run-scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install

      - name: Create service account file
        env:
          SA_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$SA_JSON" > service_account.json

      - name: Run scraper
        env:
          SERVICE_ACCOUNT_FILE: service_account.json
          SHEET_NAME: Matchday Research Board
          SOURCES_SHEET_NAME: Sources
          OUTPUT_SHEET: Games
        run: |
          python scrape_ticket_releases.py
